### ISSUE TITLE
[Bug]: flag `settngs.gitea-timeout-second` not effective

### ISSUE THREAD

**Issue by sinlov** [woodpecker-kit/woodpecker-gitea-cc-release#15]
### Component

cli

### Describe the bug

```yml
labels:
  backend: docker
steps:
  woodpecker-gitea-cc-release:
    image: sinlov/woodpecker-gitea-cc-release:latest # https://hub.docker.com/r/sinlov/woodpecker-gitea-cc-release
    pull: false
    settings:
      # debug: true
      gitea-timeout-second: 120 # gitea release api timeout second, default 60, less 30
```

not effective

### System Info

```shell
any system
```

### Validations

- [X] Read the [Contributing Guidelines](../blob/main/.github/CONTRIBUTING_DOC/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](../issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already.
